name: Checks

on:
    pull_request:
        branches:
            - main

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.13.1

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements.dev.txt

            - name: Test
              run: sudo docker compose run --rm app sh -c "python manage.py test"

            - name: Lint
              run: sudo docker compose run --rm app sh -c "flake8"